name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=14.10

      - name: Set default Xcode 12.3
        run: |
          xcode-select --install # Install Command Line Tools if you haven't already.
          sudo xcode-select --switch /Library/Developer/CommandLineTools # Enable command line tools

      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: nuget restore

      - name: Build
        run: msbuild FameTracker/FameTracker.iOS/FameTracker.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
